# **Exploring libraries in numpy**


In [ ]:
import numpy as np

## Numpy arrays

In [ ]:
x = [1,2,3,4,5]
arr = np.array(x)
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#dimension of an array
arr.ndim

1

In [ ]:
#datatype of an array
arr.dtype

dtype('int64')

In [ ]:
#size of an array
arr.size

5

In [ ]:
#shape of an array
arr.shape

(5,)

## Two dimensional arrays

In [ ]:
a = ([2,3,4],[4,5,6])
twodarr = np.array(a)
print(twodarr )

[[2 3 4]
 [4 5 6]]


In [ ]:
twodarr.ndim #dimension

2

In [ ]:
twodarr.dtype #datatype

dtype('int64')

In [ ]:
twodarr.shape #shape

(2, 3)

In [ ]:
twodarr.size #size


6

## Creation of series of elements in an array

In [ ]:
seqarr = np.arange(1,100,1)
seqarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
evenarr = np.arange(1,21,2)
evenarr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
oddarray = np.arange(1,22,2)
oddarray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# **Numpy Functions**

In [ ]:
zeroarr = np.zeros(4)     #one dimensional
zeroarr

array([0., 0., 0., 0.])

In [ ]:
zeroarr.ndim

1

In [ ]:
twod_zeroarr = np.zeros([2,3])   #two dimensional
twod_zeroarr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
onesarr = np.ones(8)
onesarr

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
onesarr.ndim

1

In [ ]:
twod_onesarr = np.ones([5,6])
twod_onesarr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
th = np.ones([3,4,3])
'''[x,y,z]--->meaning it has x layers, each layer contains y rows, and
 each row contains z elements, all initialized to 1.'''
th

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
eye = np.eye(5)  #eye function diagonally it gives 1's
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diagarr = np.diag([2,3,4,5,6])   #printing diagonal elements
diagarr

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [ ]:
#printing random values
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
c = np.random.randint(1,20,5)
print(a)
print(b)
print(c)

[ 8 13 12  1 16]
[17 11  3  5 11]
[ 5 12  5 11 18]


In [ ]:
#print values ranging from only 0 to 1
r = np.random.rand(5)


In [ ]:
r.ndim

1

In [ ]:
q = np.random.rand(4,5)
q


array([[0.47396038, 0.4919305 , 0.17423059, 0.76151943, 0.22512453],
       [0.57418368, 0.95178618, 0.36624817, 0.62005652, 0.59746175],
       [0.99287231, 0.65028596, 0.92528987, 0.84751766, 0.23407234],
       [0.8261799 , 0.29010634, 0.80045224, 0.4838487 , 0.13950056]])